generate test report

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -26,10 +26,17 @@ jobs:
       run: dotnet build --no-restore
     - name: Test with dotnet
       run: dotnet test --logger trx --results-directory "TestResults"
-    - name: Upload dotnet test results
-      uses: actions/upload-artifact@v3
-      with:
-        name: dotnet-results
-        path: TestResults
-      # Use always() to always run this step to publish test results when there are test failures
-      if: ${{ always() }}
+    # - name: Upload dotnet test results
+    #   uses: actions/upload-artifact@v3
+    #   with:
+    #     name: dotnet-results
+    #     path: TestResults
+    #   # Use always() to always run this step to publish test results when there are test failures
+    #   if: ${{ always() }}
+    - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: MS Tests            # Name of the check run which will be created
+          path: TestResults/*.trx    # Path to test results
+          reporter: dotnet-trx        # Format of test results
